function randomSplashText() {
  return splashSentences[
    Math.floor(Math.random() * (splashSentences.length - 1)) + 1
  ];
}

export { randomSplashText };

const splashSentences = [
  "The old oak tree stood majestically at the edge of the forest.",
  "She carefully examined the mysterious package that arrived this morning.",
  "The small café on the corner serves the best croissants in town.",
  "His collection of vintage records grew larger every month.",
  "The child's laughter echoed through the empty hallway.",
  "Raindrops tapped gently against the window as the storm passed.",
  "The ancient manuscript contained secrets lost for centuries.",
  "They decided to take the scenic route along the coast.",
  "The cat stretched lazily in the patch of sunlight.",
  "A forgotten photograph revealed a surprising family secret.",
  "The mountain trail became steeper with each passing mile.",
  "She planted wildflower seeds in the garden last spring.",
  "The museum's new exhibit attracted visitors from around the world.",
  "His attempt to bake bread for the first time ended in disaster.",
  "The old bookstore had shelves that reached the ceiling.",
  "The annual festival brought the entire community together.",
  "The motorcycle roared to life with a simple turn of the key.",
  "Footprints in the sand disappeared with the rising tide.",
  "The detective carefully analyzed the evidence from the crime scene.",
  "A rainbow appeared after the brief summer shower.",
  "The abandoned house at the end of the street sparked numerous legends.",
  "They celebrated their anniversary with a dinner by candlelight.",
  "The artist spent months perfecting the intricate mural.",
  "Children built sandcastles along the shoreline all afternoon.",
  "The recipe had been passed down through generations.",
  "Stars twinkled brightly in the clear night sky.",
  "The professor's lecture captivated the entire audience.",
  "A gentle breeze rustled the leaves in the garden.",
  "The antique clock still kept perfect time after all these years.",
  "She wrote poetry during quiet moments at dawn.",
  "The dog wagged its tail excitedly at the sight of its owner.",
  "Fresh snow blanketed the landscape in pristine white.",
  "The orchestra performed a beautiful symphony that evening.",
  "A secret passage was discovered behind the bookcase.",
  "The aroma of freshly baked bread filled the kitchen.",
  "Birds gathered around the newly installed feeder in the backyard.",
  "The mechanic diagnosed the problem with the engine immediately.",
  "A brilliant sunset painted the sky with vibrant colors.",
  "The novel's unexpected ending left readers stunned.",
  "They built a campfire and shared stories until midnight.",
  "The old photograph album contained memories from decades past.",
  "Waves crashed against the rocky cliffs with tremendous force.",
  "The chef's signature dish always impressed dinner guests.",
  "Fireflies illuminated the summer garden with their gentle glow.",
  "The historic building was carefully restored to its former glory.",
  "Butterflies fluttered among the wildflowers in the meadow.",
  "The chess match between grandmasters lasted for hours.",
  "She collected seashells during her morning walks on the beach.",
  "The scent of pine trees filled the crisp mountain air.",
  "A heated debate erupted during the town hall meeting.",
  "The pianist's fingers danced gracefully across the keys.",
  "Fog rolled in from the bay, obscuring the city skyline.",
  "The garden maze challenged visitors with its complex design.",
  "They watched shooting stars from the rooftop observatory.",
  "The handcrafted jewelry piece was truly one of a kind.",
  "Snow began falling just as the holiday celebration commenced.",
  "The athlete broke the world record by a fraction of a second.",
  "Ancient ruins revealed clues about a long-forgotten civilization.",
  "The documentary highlighted environmental issues facing the planet.",
  "Fresh herbs from the garden enhanced the flavor of the soup.",
  "Lightning illuminated the night sky during the intense storm.",
  "The theater production received a standing ovation on opening night.",
  "Wild horses roamed freely across the vast prairie.",
  "The treasure map led explorers to an unexpected discovery.",
  "Autumn leaves crunched beneath their feet during the hike.",
  "The crystal clear lake reflected the surrounding mountain peaks.",
  "She solved the complex puzzle in record time.",
  "The classic film still resonated with audiences decades later.",
  "A flock of geese flew overhead in perfect formation.",
  "The software update fixed several longstanding issues.",
  "Tiny seedlings sprouted from the rich, dark soil.",
  "The jazz quartet improvised a mesmerizing melody.",
  "A layer of frost covered the garden on the cold morning.",
  "The astronomer discovered a previously unknown celestial body.",
  "Wildflowers bloomed abundantly after the spring rains.",
  "The handwritten letter arrived unexpectedly after many years.",
  "Dolphins played in the wake of the sailing ship.",
  "The historical novel transported readers to another era.",
  "A helicopter circled overhead, searching for the lost hiker.",
  "The bronze sculpture gleamed in the afternoon sunlight.",
  "Children sledded down the hill after the first snowfall.",
  "The intricate tapestry depicted scenes from ancient mythology.",
  "Bees buzzed busily among the flowering plants.",
  "The teenager won first prize in the science competition.",
  "Shadows grew longer as the sun began to set.",
  "The vintage automobile attracted attention wherever it went.",
  "She practiced the violin diligently every morning.",
  "The mysterious disappearance remained unsolved for decades.",
  "Fresh paint brightened the walls of the renovated room.",
  "The pilot navigated skillfully through the turbulent storm.",
  "Tourists marveled at the ancient architectural wonder.",
  "The harvest moon illuminated the countryside with golden light.",
  "Their friendship had endured through decades of challenges.",
  "The scientist's groundbreaking discovery changed the field forever.",
  "Autumn colors transformed the landscape into a vibrant canvas.",
  "The robot performed complex tasks with precision and efficiency.",
  "Whales breached the surface of the ocean in spectacular displays.",
];
