name: Backend Start Test

on:
  push:
    branches:
      - main
      - develop
      - develop/*
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - develop
      - develop/*
    paths:
      - 'backend/**'

jobs:
  start-test:
    name: Check Backend Startup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: backend

      - name: Start Backend
        run: pnpm run start &
        working-directory: backend

      - name: Wait for Server to Start
        run: sleep 5

      - name: Check if Server is Running
        run: curl -I http://localhost:3000 || exit 1