name: Frontend Build Test

on:
  push:
    branches:
      - main
      - develop
      - develop/*
  pull_request:
    branches:
      - main
      - develop
      - develop/*

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Install Dependencies
        run: pnpm install
        working-directory: frontend

      - name: Build Project
        run: pnpm run build
        working-directory: frontend
